### ISSUE TITLE
recording target problem.

### ISSUE THREAD

**Issue by AdamWorld** [Everyplay/everyplay-android-examples#1]
In this example, everyplay only records GLSurfaceView and doesnt record button or other controls.
But in my case, it captures all including buttons, dialogs, ...
I didn't make a GLSurfaceView, made only normal view and draw animation in onDraw() and record it.

Did i do something wrong?

**Comment by AdamWorld** [comment]
any update?

**Comment by aet** [comment]
I don't see an issue.

depending on UI widget used and the device/android version/app configuration, the graphics may be drawn using GLES and they get recorded
